import runBigwigTests from "./testBigwig.js";
import runBAMTests from "./testBAM.js";
import runBAMIndexTests from "./testBamIndex.js";
import runAedTests from "./testAED.js";
import runBedTests from "./testBED.js";
import runBEDGraphTests from "./testBEDGraph.js";

runBigwigTests();
runBAMTests();
runBAMIndexTests();
runAedTests();
runBedTests();
runBEDGraphTests();
// runBufferedReaderTests();
// runCoverageColoredRenderingTests();
// runWigTests();
// runGFFTests();
// runFastaTests();
// runSegTests();
// runTabixTests();
// runGenomeTests();
// runTDFTests();
// runSampleInformationTests();
// runHtsgetTests();
// runSessionTests();
// runVariantTests();
// runBrowserTests();
// runUtilTests();
// runIgvXhrTests();
// runCRAMTests();
// runCoreTests();
