name: Build Status

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '19.x'
    - name: Install dependencies
      run: npm install
      env:
        DEFAULT_BRANCH: master
    - run: npm test
      env:
        DEFAULT_BRANCH: master
